server:
  port: 9988

#datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 50000
      connection-timeout: 60000
      connection-test-query: SELECT 1

  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 10000



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
# 需要打印SQL 放开这个注释
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false



logging:
  config: classpath:logback.xml